#!/bin/bash


if [ $(id -u) != 0 ] ; then
   echo "You need to run this as root"
   exit 1
fi

set -xe

#Ports:
#Ubuntu-mate 18.04.3
#Debain 9

#apt deb packages needed for all these package installations:
#
apt install -y\
 build-essential\
 gcc-multilib\
 csh\
 devhelp\
 sox\
 at\
 imagemagick-doc\
 imagemagick\
 graphviz-dev\
 curl\
 pkgconf\
 autoconf\
 libtool\
 automake\
 sqlite\
 libtool-bin\
 libssl-dev\
 bison\
 libreadline-dev\
 libsqlite3-dev\
 liblua5.3-dev\
 lua5.3


# liblua5.2-dev\
# lua5.2

# liblua5.3-dev\
# lua5.3
