#!/bin/bash

# We have been unable to use the http.conf file generated by the ondemand
# generator script, but it does give a hint as to what http.conf should
# look like.


set -ex

ONDEMAND_PREFIX=$(../config ONDEMAND_PREFIX)

generate="$ONDEMAND_PREFIX/ood-portal-generator/bin/generate"


sed\
 -e "s!@ONDEMAND_PREFIX@!${ONDEMAND_PREFIX}!g"\
 -e "s!@HOSTNAME@!${HOSTNAME}!g"\
 httpd.conf.ymlin > httpd.conf.yml

$generate -c httpd.conf.yml

rm httpd.conf.yml
