# This is a GNU make file that uses GNU make make extensions

# Where to install selected files in this directory.  We must use = and
# not := because PREFIX is set later when common.make is included.  It's
# (= and/or :=) a GNU make thing.
INSTALL_DIR = $(PREFIX)/pun

include ../quickbuild.make
